#!/usr/bin/env bash
#
# Download the official Elixir anti-pattern guides, split each one into a
# reference file per anti-pattern, and regenerate the catalog in SKILL.md.
#
# Markdown is parsed with ast-grep (tree-sitter): every `##` shows up as an
# atx_heading, so we take the line of each heading and slice the document from
# one heading to the line before the next. For each anti-pattern:
#   - the `## Title` becomes the file's `#`, and every deeper heading shifts up
#     two levels (`#### Example` -> `## Example`), skipping `#`-lines inside
#     ```elixir blocks;
#   - the "Problem" body is lifted into the SKILL.md catalog (always in context),
#     while the example and refactoring stay in references/<type>/<slug>.md.
# The list between the index markers in SKILL.md is rebuilt from those titles and
# problem bodies. Re-run any time to refresh from upstream.
set -euo pipefail

cd "$(dirname "$0")"

base="https://elixir.hexdocs.pm"
out="references"
skill="SKILL.md"
tmp="$(mktemp -d)"
idx="$tmp/index.md"
trap 'rm -rf "$tmp"' EXIT

rm -rf "$out"
: > "$idx"

# category slug -> label, in the order they appear in the catalog
cats=(code design macro process)
declare -A labels=(
	[code]="Code"
	[design]="Design"
	[macro]="Meta-programming"
	[process]="Process"
)

slugify() {
	printf '%s' "$1" | tr '[:upper:]' '[:lower:]' \
		| sed -E 's/`//g; s/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

for cat in "${cats[@]}"; do
	url="$base/$cat-anti-patterns.md"
	src="$tmp/$cat.md"
	echo "downloading $url" >&2
	curl -fsSL "$url" -o "$src"

	mkdir -p "$out/$cat"
	total="$(wc -l < "$src")"

	# `line<TAB>title` for every `##` anti-pattern heading, in document order.
	mapfile -t headings < <(
		ast-grep run -p '## $$$' -l md "$src" \
			| sed -E 's/^[^:]+:([0-9]+):## /\1\t/'
	)

	printf '\n### %s\n' "${labels[$cat]}" >> "$idx"

	n=${#headings[@]}
	for ((i = 0; i < n; i++)); do
		line="${headings[i]%%$'\t'*}"
		title="${headings[i]#*$'\t'}"

		if ((i + 1 < n)); then
			end=$((${headings[i + 1]%%$'\t'*} - 1))
		else
			end="$total"
		fi

		slug="$(slugify "$title")"
		dest="$out/$cat/$slug.md"

		# reference file gets a provenance comment; the example/refactoring follow.
		printf '<!-- Source: %s. Generated by build.sh; do not edit by hand. -->\n\n' "$url" > "$dest"

		# catalog entry: a linked heading, then the lifted problem body.
		printf '\n#### [%s](%s)\n\n' "$title" "$dest" >> "$idx"

		# One pass over the section: shift headings up, route the Problem body to the
		# catalog (idx) and everything else to the reference file (dest). Fenced code
		# is copied verbatim and never treated as headings.
		sed -n "${line},${end}p" "$src" | awk -v dest="$dest" -v idx="$idx" '
      BEGIN { route = "dest" }
      function out(s) { if (route == "idx") print s >> idx; else print s >> dest }
      /^```/      { fence = !fence; out($0); next }
      fence       { out($0); next }
      /^##### /   { l = $0; sub(/^##/, "", l); out(l); next }   # h5 -> h3
      /^#### /    {                                             # h4 section boundary
                    if ($0 == "#### Problem") { route = "idx" }
                    else { route = "dest"; l = $0; sub(/^##/, "", l); out(l) }
                    next
                  }
      /^## /      { route = "dest"; l = $0; sub(/^#/, "", l); out(l); next }  # h2 title -> h1
      { out($0) }
    '
	done
done

# Splice the freshly built list between the index markers in SKILL.md.
awk '
  FNR == NR { block = block $0 ORS; next }
  /<!-- index:start -->/ { print; printf "%s", block; skip = 1; next }
  /<!-- index:end -->/   { skip = 0; print ""; print; next }
  !skip { print }
' "$idx" "$skill" > "$skill.tmp" && mv "$skill.tmp" "$skill"

count="$(find "$out" -name '*.md' | wc -l | tr -d ' ')"
echo "wrote $count reference files and refreshed $skill" >&2
